[default]
    phrase_file_path='data/an_phrases.json'
    results_path='data/results'
    encoder='dpr'
    vecop='sum'
    sentence_encoding=true
    strict=true
    control=0
    batch_size=1000
    openai_auth_file='openai_auth.json'

